main:
  - name: Menüstruktur
    url: /docs/menuebaum/
    weight: 30
  - name: Demonstrator
    url: /demo/
    weight: 40
  - name: Anwendungsbeispiele
    url: /beispiele/
    weight: 50  
  - name: Firmware
    url: /docs/firmware/
    weight: 60
